config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome', as: 'welcome'
  get 'portfolio' => 'pages#portfolio', as: 'portfolio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'unslider', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <ul>
      <li>Léo</li>
      <li><%= link_to 'Weclome', welcome_path %></li>
      <li><%= link_to 'Portfolio', portfolio_path %></li>
      <li>About</li>
      <li>Contact</li>
    </ul>
  </nav>
</header>
<%= yield %>
<footer>
  <a href="">GitHub</a>
  <a href="">LinkedIn</a>
  <a href="">Copyright</a>
</footer>
</body>
</html>

app/views/pages/portfolio.html.erb
<main>
  <div class="banner">
    <ul>
        <li><img src="https://photos-4.dropbox.com/t/2/AABGUcl9Y87ZhaHxJNHebZCnnqt-NEpBd6gV-u76L4B7Fg/12/125279238/png/32x32/1/1435788000/0/2/1.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/DiOLfzxH53unv1MWr83N1SwVCFfruMCtDsKFtC3nyNw?size=1024x768&size_mode=2"/></li>
        <li><img src="https://photos-5.dropbox.com/t/2/AAApoXW14hYIdad7mAebHWnbvmyCqDVg4BTvrBNIucdS4w/12/125279238/png/32x32/1/1435788000/0/2/2.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/5Lu0g2Pj1O4L0LNE9VqwgkSdOqxWRHdvYyAwkVq1xr8?size=1024x768&size_mode=2"/></li>
        <li><img src="https://photos-4.dropbox.com/t/2/AAAVeJeqYYldws9oOO3RvsB-Xdga8Cs9jK1jk_CHcAvq-w/12/125279238/png/32x32/1/1435788000/0/2/3.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/_EMVnhSFCcpKPv_bijV60p8P_Zn633OLwwhbENDR-14?size=1024x768&size_mode=2"/></li>
    </ul>
</div>
  <section>
    <div>
      <img src="https://photos-4.dropbox.com/t/2/AABGUcl9Y87ZhaHxJNHebZCnnqt-NEpBd6gV-u76L4B7Fg/12/125279238/png/32x32/1/1435788000/0/2/1.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/DiOLfzxH53unv1MWr83N1SwVCFfruMCtDsKFtC3nyNw?size=1024x768&size_mode=2"/>
      <h1>Projet 1</h1>
      <p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine.</p>
      <a href="">Learn more</a>
    </div>
    <div>
      <img src="https://photos-5.dropbox.com/t/2/AAApoXW14hYIdad7mAebHWnbvmyCqDVg4BTvrBNIucdS4w/12/125279238/png/32x32/1/1435788000/0/2/2.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/5Lu0g2Pj1O4L0LNE9VqwgkSdOqxWRHdvYyAwkVq1xr8?size=1024x768&size_mode=2"/>
      <h1>Projet 2</h1><p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine.</p>
      <a href="">Learn more</a>
    </div>
    <div>
      <img src="https://photos-4.dropbox.com/t/2/AAAVeJeqYYldws9oOO3RvsB-Xdga8Cs9jK1jk_CHcAvq-w/12/125279238/png/32x32/1/1435788000/0/2/3.png/CIa43jsgASACIAMgBCAFIAYgBygCKAM/_EMVnhSFCcpKPv_bijV60p8P_Zn633OLwwhbENDR-14?size=1024x768&size_mode=2"/>
      <h1>Projet 3</h1><p>Emensis itaque difficultatibus multis et nive obrutis callibus plurimis ubi prope Rauracum ventum est ad supercilia fluminis Rheni, resistente multitudine.</p>
      <a href="">Learn more</a>
    </div>
  </section>
</main>

app/views/pages/welcome.html.erb
<main>
  <h1>Hello, I'm making my portfolio !</h1>
  <%= link_to 'Portfolio', portfolio_path %>
</main>